# Generated by Django 6.0 on 2026-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly budget limit', max_digits=12),
        ),
    ]
