# Generated by Django 6.0 on 2026-01-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_monthly_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccess',
            name='level',
            field=models.CharField(choices=[('VIEW', 'Viewer (Read Only)'), ('ADD', 'Editor (Add/Edit Transactions)'), ('FULL', 'Full Control')], default='VIEW', max_length=10),
        ),
    ]
