# Generated by Django 6.0 on 2026-01-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
