# Generated by Django 6.0 on 2026-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maintenancestate_logging_channel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancestate',
            options={'verbose_name': 'System Control', 'verbose_name_plural': 'System Control'},
        ),
        migrations.AddField(
            model_name='maintenancestate',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
    ]
