# Generated by Django 6.0 on 2026-02-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_maintenancestate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='expected_duration',
            field=models.CharField(blank=True, help_text="e.g. '2 hours', '15 mins'", max_length=100, null=True),
        ),
    ]
