# Generated by Django 6.0 on 2026-02-14 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BASIC', 'Basic (Free)'), ('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=6)),
                ('max_accounts', models.PositiveIntegerField(blank=True, default=1, help_text='Max number of accounts allowed. None for unlimited.', null=True)),
                ('max_shared_accounts', models.PositiveIntegerField(blank=True, default=0, help_text='Max number of shared accounts allowed. None for unlimited.', null=True)),
                ('pdf_export_limit', models.PositiveIntegerField(default=5, help_text='Monthly PDF export limit.')),
                ('can_export_csv', models.BooleanField(default=False, help_text='Allow exporting to CSV/Excel')),
                ('has_advanced_analytics', models.BooleanField(default=False, help_text='Access to advanced analytics')),
                ('has_team_collaboration', models.BooleanField(default=False, help_text='Access to fiture team tools')),
                ('has_basic_app_features', models.BooleanField(default=True, help_text='Basic features like adding transactions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pdf_exports_used', models.PositiveIntegerField(default=0)),
                ('last_usage_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
