# Generated by Django 6.0 on 2026-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_create_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='has_advanced_analytics',
            new_name='allow_advanced_analytics',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_export_csv',
            new_name='allow_export',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(default='PAID', help_text='Payment status (e.g., PAID, PENDING, FAILED)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_team_collaboration',
            field=models.BooleanField(default=False, help_text='Access to team tools'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pdf_export_limit',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Monthly PDF export limit. None means unlimited.', null=True),
        ),
    ]
