# Generated by Django 6.0 on 2026-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_logout_time',
            field=models.DateTimeField(blank=True, help_text='If set, user will be forced to logout if their session started before this time.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been frozen.'),
        ),
    ]
