# Generated by Django 6.0 on 2026-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message to send to all users')),
                ('type', models.CharField(choices=[('LOW_BALANCE', 'Low Balance'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('LARGE_TRANSACTION', 'Large Transaction'), ('SHARED_ACTIVITY', 'Shared Activity'), ('MAINTENANCE', 'Maintenance')], default='MAINTENANCE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
